import tempfile
import unittest
from pathlib import Path


class DiscordSnowflakeTests(unittest.IsolatedAsyncioTestCase):
    def test_practice_ids_are_postgres_generated(self):
        from backend.database.db import _translate_sql
        from backend.practice.storage import SCHEMA
        from backend.analysis.service import SCHEMA as ANALYSIS_SCHEMA

        statements = [
            statement for statement in SCHEMA.split(";")
            if "CREATE TABLE IF NOT EXISTS practice_" in statement
        ]
        self.assertEqual(len(statements), 3)
        for statement in statements[:2]:
            translated = _translate_sql(statement)
            self.assertIn("GENERATED BY DEFAULT AS IDENTITY", translated)
        analysis_statement = next(
            statement for statement in ANALYSIS_SCHEMA.split(";")
            if "CREATE TABLE IF NOT EXISTS analysis_revisions" in statement
        )
        self.assertIn(
            "GENERATED BY DEFAULT AS IDENTITY",
            _translate_sql(analysis_statement),
        )

    async def test_discord_snowflake_round_trip(self):
        from backend.database import db

        snowflake = 1546225609967935620
        original_path = db.DB_PATH
        with tempfile.TemporaryDirectory() as directory:
            db.DB_PATH = Path(directory) / "snowflake.db"
            try:
                await db.initialize_database()
                await db.get_or_create_user(
                    snowflake,
                    "snowflake-user",
                    "Snowflake User",
                )
                connection = await db.connect()
                try:
                    row = await (
                        await connection.execute(
                            "SELECT discord_id FROM users WHERE discord_id=?",
                            (snowflake,),
                        )
                    ).fetchone()
                    self.assertEqual(int(row["discord_id"]), snowflake)
                finally:
                    await connection.close()
            finally:
                db.DB_PATH = original_path


if __name__ == "__main__":
    unittest.main()
