import aiosqlite
import os
import re
from pathlib import Path
from backend.database.migrations import (
    DISCORD_ID_MIGRATION_VERSION,
    SCHEMA_VERSION,
    record_version,
)

try:
    from psycopg import AsyncConnection, connect as sync_pg_connect
    from psycopg.rows import dict_row
except ImportError:  # SQLite development installs need not carry PostgreSQL
    AsyncConnection = None
    sync_pg_connect = None
    dict_row = None


DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
if os.getenv("BISHOPLY_ENV", "development").strip().lower() == "production":
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL is required in production")
    if not DATABASE_URL.startswith(("postgres://", "postgresql://")):
        raise RuntimeError("DATABASE_URL must be a PostgreSQL URL in production")


def using_postgres() -> bool:
    return DATABASE_URL.startswith(("postgres://", "postgresql://"))


class _CompatCursor:
    def __init__(self, cursor=None, rows=()):
        self._cursor = cursor
        self._rows = list(rows)
        self.rowcount = getattr(cursor, "rowcount", -1) if cursor else 0

    @property
    def lastrowid(self):
        return None

    async def fetchone(self):
        if self._cursor is not None:
            return await self._cursor.fetchone()
        return self._rows[0] if self._rows else None

    async def fetchall(self):
        if self._cursor is not None:
            return await self._cursor.fetchall()
        return self._rows


def _compat_row_factory(cursor):
    """Dict-like rows that also preserve legacy integer indexing."""
    class Row(dict):
        def __getitem__(self, key):
            if isinstance(key, int):
                return tuple(self.values())[key]
            return super().__getitem__(key)

    def make(values):
        # psycopg calls the row-factory builder for every cursor, including
        # DDL/non-row statements where description is None.  Resolve column
        # names only when an actual row is materialized.
        names = [column.name for column in (cursor.description or ())]
        return Row(zip(names, values))

    return make


def _translate_sql(sql: str) -> str:
    sql = sql.replace("BEGIN IMMEDIATE", "BEGIN")
    was_ignore = bool(re.search(r"INSERT\s+OR\s+IGNORE\s+INTO", sql, flags=re.I))
    sql = re.sub(r"INSERT\s+OR\s+IGNORE\s+INTO", "INSERT INTO", sql, flags=re.I)
    sql = re.sub(r"INTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", sql, flags=re.I)
    if was_ignore and "ON CONFLICT" not in sql.upper():
        suffix = ""
        match = re.search(r"\s+RETURNING\s+.+$", sql, flags=re.I | re.S)
        if match:
            suffix, sql = match.group(0), sql[:match.start()]
        sql = sql.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING" + suffix
    return sql.replace("?", "%s")


class PostgresCompatConnection:
    """Small async DB facade retaining the established aiosqlite API.

    Application services can continue to use parameterized queries and async
    cursors while production uses psycopg/PostgreSQL transaction semantics.
    """
    backend = "postgres"

    def __init__(self, connection):
        self._connection = connection

    async def execute(self, sql, parameters=()):
        if sql.strip().upper().startswith("PRAGMA"):
            return _CompatCursor(rows=())
        cursor = await self._connection.execute(_translate_sql(sql), parameters or ())
        return _CompatCursor(cursor)

    async def executescript(self, script):
        try:
            for statement in script.split(";"):
                if statement.strip():
                    await self.execute(statement)
        except Exception:
            await self.rollback()
            raise

    async def commit(self):
        await self._connection.commit()

    async def rollback(self):
        await self._connection.rollback()

    async def close(self):
        await self._connection.close()


class PostgresSyncCompatConnection:
    backend = "postgres"
    def __init__(self, connection):
        self._connection = connection
    def execute(self, sql, parameters=()):
        if sql.strip().upper().startswith("PRAGMA"):
            return _SyncNoopCursor()
        return self._connection.execute(_translate_sql(sql), parameters or ())
    def commit(self): self._connection.commit()
    def rollback(self): self._connection.rollback()
    def close(self): self._connection.close()


class _SyncNoopCursor:
    rowcount = 0
    lastrowid = None
    def fetchone(self): return None
    def fetchall(self): return []


def sync_connect():
    if using_postgres():
        if sync_pg_connect is None:
            raise RuntimeError("psycopg is required for PostgreSQL DATABASE_URL")
        return PostgresSyncCompatConnection(sync_pg_connect(DATABASE_URL, row_factory=_compat_row_factory))
    import sqlite3
    db = sqlite3.connect(DB_PATH, timeout=30)
    db.row_factory = sqlite3.Row
    db.execute("PRAGMA foreign_keys = ON")
    return db


class _CompatNoopConnection:
    backend = "sqlite"

DB_PATH = Path(os.getenv("BISHOPLY_SQLITE_PATH", "bishoply.db"))

CURRENT_RATING_MODEL = "bishoply-glicko2-v2"
DEFAULT_RATING_POOL = "standard"


BASE_SCHEMA = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    discord_id BIGINT NOT NULL UNIQUE,
    username TEXT NOT NULL,
    display_name TEXT,
    avatar_url TEXT,
    level INTEGER NOT NULL DEFAULT 1,
    xp INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ratings (
    user_id INTEGER PRIMARY KEY,
    rating REAL NOT NULL DEFAULT 1200.0,
    peak_rating REAL NOT NULL DEFAULT 1200.0,
    rating_deviation REAL NOT NULL DEFAULT 350.0,
    volatility REAL NOT NULL DEFAULT 0.06,
    provisional INTEGER NOT NULL DEFAULT 1,
    rated_games INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    draws INTEGER NOT NULL DEFAULT 0,
    games_played INTEGER NOT NULL DEFAULT 0,
    current_win_streak INTEGER NOT NULL DEFAULT 0,
    best_win_streak INTEGER NOT NULL DEFAULT 0,
    last_rated_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS games (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    public_id TEXT NOT NULL UNIQUE,
    white_user_id INTEGER,
    black_user_id INTEGER,
    mode TEXT NOT NULL DEFAULT 'casual',
    rating_pool TEXT NOT NULL DEFAULT 'standard',
    status TEXT NOT NULL DEFAULT 'waiting',
    starting_fen TEXT NOT NULL,
    current_fen TEXT NOT NULL,
    result TEXT,
    termination_reason TEXT,
    rated_eligible INTEGER NOT NULL DEFAULT 1,
    integrity_status TEXT NOT NULL DEFAULT 'pending',
    integrity_reason TEXT,
    integrity_risk_score INTEGER NOT NULL DEFAULT 0,
    rating_model TEXT,
    rating_processed INTEGER NOT NULL DEFAULT 0,
    white_rating_before REAL,
    white_rating_after REAL,
    white_rating_change REAL,
    black_rating_before REAL,
    black_rating_after REAL,
    black_rating_change REAL,
    white_rd_before REAL,
    white_rd_after REAL,
    black_rd_before REAL,
    black_rd_after REAL,
    started_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY(white_user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    FOREIGN KEY(black_user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS game_moves (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL,
    move_number INTEGER NOT NULL,
    ply INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    color TEXT NOT NULL,
    uci TEXT NOT NULL,
    san TEXT NOT NULL,
    fen_after TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(game_id)
        REFERENCES games(id)
        ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    UNIQUE(game_id, ply)
);
"""


POST_MIGRATION_SCHEMA = """
CREATE TABLE IF NOT EXISTS skill_ratings (
    user_id INTEGER NOT NULL,
    pool TEXT NOT NULL DEFAULT 'standard',
    rating REAL NOT NULL DEFAULT 1500.0,
    peak_rating REAL NOT NULL DEFAULT 1500.0,
    rating_deviation REAL NOT NULL DEFAULT 350.0,
    volatility REAL NOT NULL DEFAULT 0.06,
    provisional INTEGER NOT NULL DEFAULT 1,
    rated_games INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    draws INTEGER NOT NULL DEFAULT 0,
    current_win_streak INTEGER NOT NULL DEFAULT 0,
    best_win_streak INTEGER NOT NULL DEFAULT 0,
    model_version TEXT NOT NULL DEFAULT 'bishoply-glicko2-v2',
    last_rated_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, pool),
    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS progression (
    user_id INTEGER PRIMARY KEY,
    sr INTEGER NOT NULL DEFAULT 2500,
    peak_sr INTEGER NOT NULL DEFAULT 2500,
    total_sr_earned INTEGER NOT NULL DEFAULT 0,
    games_rewarded INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS external_chess_accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    provider TEXT NOT NULL,
    external_username TEXT NOT NULL,
    ownership_status TEXT
        NOT NULL DEFAULT 'unverified_public',
    active INTEGER NOT NULL DEFAULT 1,
    linked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_refreshed_at TIMESTAMP,
    UNIQUE (user_id, provider),
    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS external_rating_snapshots (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    external_account_id INTEGER NOT NULL,
    chess_rapid INTEGER,
    chess_blitz INTEGER,
    chess_bullet INTEGER,
    chess_daily INTEGER,
    fetched_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    source TEXT NOT NULL,
    FOREIGN KEY(external_account_id)
        REFERENCES external_chess_accounts(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS competitive_transactions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER NOT NULL UNIQUE,
    pool TEXT NOT NULL,
    rating_model TEXT NOT NULL,
    decision TEXT NOT NULL,
    decision_reason TEXT,
    risk_score INTEGER NOT NULL DEFAULT 0,
    white_user_id INTEGER NOT NULL,
    black_user_id INTEGER NOT NULL,
    white_rating_before REAL NOT NULL,
    white_rating_after REAL NOT NULL,
    white_rating_change REAL NOT NULL,
    white_rd_before REAL NOT NULL,
    white_rd_after REAL NOT NULL,
    white_volatility_before REAL NOT NULL,
    white_volatility_after REAL NOT NULL,
    black_rating_before REAL NOT NULL,
    black_rating_after REAL NOT NULL,
    black_rating_change REAL NOT NULL,
    black_rd_before REAL NOT NULL,
    black_rd_after REAL NOT NULL,
    black_volatility_before REAL NOT NULL,
    black_volatility_after REAL NOT NULL,
    white_sr_before INTEGER NOT NULL,
    white_sr_after INTEGER NOT NULL,
    white_sr_change INTEGER NOT NULL,
    black_sr_before INTEGER NOT NULL,
    black_sr_after INTEGER NOT NULL,
    black_sr_change INTEGER NOT NULL,
    result TEXT NOT NULL,
    reversed INTEGER NOT NULL DEFAULT 0,
    reversed_at TIMESTAMP,
    reversal_reason TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(game_id)
        REFERENCES games(id)
        ON DELETE CASCADE,
    FOREIGN KEY(white_user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    FOREIGN KEY(black_user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS integrity_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    game_id INTEGER,
    user_id INTEGER,
    code TEXT NOT NULL,
    severity TEXT NOT NULL,
    risk_points INTEGER NOT NULL DEFAULT 0,
    details_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(game_id)
        REFERENCES games(id)
        ON DELETE CASCADE,
    FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_games_public_id
ON games(public_id);

CREATE INDEX IF NOT EXISTS idx_games_white
ON games(white_user_id);

CREATE INDEX IF NOT EXISTS idx_games_black
    ON games(black_user_id);
CREATE INDEX IF NOT EXISTS idx_games_white_updated
    ON games(white_user_id, updated_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_games_black_updated
    ON games(black_user_id, updated_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_games_status
ON games(status);

CREATE INDEX IF NOT EXISTS idx_games_integrity
ON games(integrity_status);

CREATE INDEX IF NOT EXISTS idx_games_completed
ON games(completed_at);

CREATE INDEX IF NOT EXISTS idx_game_moves_game
ON game_moves(game_id);

CREATE INDEX IF NOT EXISTS idx_skill_rating_pool
ON skill_ratings(pool, rating DESC);

CREATE INDEX IF NOT EXISTS idx_skill_rating_user
ON skill_ratings(user_id);

CREATE INDEX IF NOT EXISTS idx_progression_sr
ON progression(sr DESC);

CREATE INDEX IF NOT EXISTS idx_external_provider_username
ON external_chess_accounts(provider, external_username);

CREATE INDEX IF NOT EXISTS idx_external_snapshot_account
ON external_rating_snapshots(external_account_id, fetched_at DESC);

CREATE INDEX IF NOT EXISTS idx_integrity_game
ON integrity_events(game_id);

CREATE INDEX IF NOT EXISTS idx_integrity_user
ON integrity_events(user_id);

CREATE INDEX IF NOT EXISTS idx_competitive_white
ON competitive_transactions(white_user_id);

CREATE INDEX IF NOT EXISTS idx_competitive_black
ON competitive_transactions(black_user_id);
"""


GAME_MIGRATIONS = [
    (
        "rating_pool",
        """
        ALTER TABLE games
        ADD COLUMN rating_pool TEXT
        NOT NULL DEFAULT 'standard'
        """,
    ),
    (
        "rated_eligible",
        """
        ALTER TABLE games
        ADD COLUMN rated_eligible INTEGER
        NOT NULL DEFAULT 1
        """,
    ),
    (
        "integrity_status",
        """
        ALTER TABLE games
        ADD COLUMN integrity_status TEXT
        NOT NULL DEFAULT 'pending'
        """,
    ),
    (
        "integrity_reason",
        """
        ALTER TABLE games
        ADD COLUMN integrity_reason TEXT
        """,
    ),
    (
        "integrity_risk_score",
        """
        ALTER TABLE games
        ADD COLUMN integrity_risk_score INTEGER
        NOT NULL DEFAULT 0
        """,
    ),
    (
        "rating_model",
        """
        ALTER TABLE games
        ADD COLUMN rating_model TEXT
        """,
    ),
    (
        "rating_processed",
        """
        ALTER TABLE games
        ADD COLUMN rating_processed INTEGER
        NOT NULL DEFAULT 0
        """,
    ),
    (
        "white_rating_before",
        """
        ALTER TABLE games
        ADD COLUMN white_rating_before REAL
        """,
    ),
    (
        "white_rating_after",
        """
        ALTER TABLE games
        ADD COLUMN white_rating_after REAL
        """,
    ),
    (
        "white_rating_change",
        """
        ALTER TABLE games
        ADD COLUMN white_rating_change REAL
        """,
    ),
    (
        "black_rating_before",
        """
        ALTER TABLE games
        ADD COLUMN black_rating_before REAL
        """,
    ),
    (
        "black_rating_after",
        """
        ALTER TABLE games
        ADD COLUMN black_rating_after REAL
        """,
    ),
    (
        "black_rating_change",
        """
        ALTER TABLE games
        ADD COLUMN black_rating_change REAL
        """,
    ),
    (
        "white_rd_before",
        """
        ALTER TABLE games
        ADD COLUMN white_rd_before REAL
        """,
    ),
    (
        "white_rd_after",
        """
        ALTER TABLE games
        ADD COLUMN white_rd_after REAL
        """,
    ),
    (
        "black_rd_before",
        """
        ALTER TABLE games
        ADD COLUMN black_rd_before REAL
        """,
    ),
    (
        "black_rd_after",
        """
        ALTER TABLE games
        ADD COLUMN black_rd_after REAL
        """,
    ),
    (
        "started_at",
        """
        ALTER TABLE games
        ADD COLUMN started_at TIMESTAMP
        """,
    ),
    (
        "completed_at",
        """
        ALTER TABLE games
        ADD COLUMN completed_at TIMESTAMP
        """,
    ),
]


RATING_MIGRATIONS = [
    (
        "rating_deviation",
        """
        ALTER TABLE ratings
        ADD COLUMN rating_deviation REAL
        NOT NULL DEFAULT 350.0
        """,
    ),
    (
        "volatility",
        """
        ALTER TABLE ratings
        ADD COLUMN volatility REAL
        NOT NULL DEFAULT 0.06
        """,
    ),
    (
        "provisional",
        """
        ALTER TABLE ratings
        ADD COLUMN provisional INTEGER
        NOT NULL DEFAULT 1
        """,
    ),
    (
        "rated_games",
        """
        ALTER TABLE ratings
        ADD COLUMN rated_games INTEGER
        NOT NULL DEFAULT 0
        """,
    ),
    (
        "last_rated_at",
        """
        ALTER TABLE ratings
        ADD COLUMN last_rated_at TIMESTAMP
        """,
    ),
]


async def connect():
    if using_postgres():
        if AsyncConnection is None:
            raise RuntimeError("psycopg is required for PostgreSQL DATABASE_URL")
        connection = await AsyncConnection.connect(DATABASE_URL, row_factory=_compat_row_factory)
        return PostgresCompatConnection(connection)
    db = await aiosqlite.connect(DB_PATH)

    db.row_factory = aiosqlite.Row

    await db.execute(
        "PRAGMA foreign_keys = ON;"
    )

    await db.execute(
        "PRAGMA journal_mode = WAL;"
    )

    await db.execute(
        "PRAGMA synchronous = NORMAL;"
    )

    await db.execute(
        "PRAGMA busy_timeout = 5000;"
    )

    return db


async def get_table_columns(
    db,
    table_name,
):
    if getattr(db, "backend", "sqlite") == "postgres":
        cursor = await db.execute(
            "SELECT column_name AS name FROM information_schema.columns "
            "WHERE table_schema = 'public' AND table_name = ?",
            (table_name,),
        )
    else:
        cursor = await db.execute(f"PRAGMA table_info({table_name});")

    rows = await cursor.fetchall()

    return {
        row["name"]
        for row in rows
    }


async def run_column_migrations(
    db,
    table_name,
    migrations,
):
    columns = await get_table_columns(
        db,
        table_name,
    )

    for column_name, sql in migrations:
        if column_name in columns:
            continue

        await db.execute(sql)
        columns.add(column_name)

    await db.commit()


async def bootstrap_competitive_profiles(
    db,
):
    await db.execute(
        """
        INSERT OR IGNORE INTO skill_ratings (
            user_id,
            pool,
            rating,
            peak_rating,
            rating_deviation,
            volatility,
            provisional,
            rated_games,
            model_version
        )
        SELECT
            id,
            ?,
            1500.0,
            1500.0,
            350.0,
            0.06,
            1,
            0,
            ?
        FROM users
        """,
        (
            DEFAULT_RATING_POOL,
            CURRENT_RATING_MODEL,
        ),
    )

    await db.execute(
        """
        INSERT OR IGNORE INTO progression (
            user_id,
            sr,
            peak_sr,
            total_sr_earned,
            games_rewarded
        )
        SELECT
            id,
            2500,
            2500,
            0,
            0
        FROM users
        """
    )

    await db.commit()


async def initialize_database():
    db = await connect()

    try:
        await db.executescript(BASE_SCHEMA)
        await db.commit()

        await run_column_migrations(
            db,
            "ratings",
            RATING_MIGRATIONS,
        )

        await run_column_migrations(
            db,
            "games",
            GAME_MIGRATIONS,
        )

        await db.executescript(
            POST_MIGRATION_SCHEMA
        )

        await db.execute(
            "CREATE TABLE IF NOT EXISTS schema_migrations (version INTEGER PRIMARY KEY, applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP)"
        )
        await record_version(db, SCHEMA_VERSION)

        await db.commit()

        await bootstrap_competitive_profiles(
            db
        )
    except Exception:
        await db.rollback()
        raise

    finally:
        await db.close()


async def migrate_discord_id_columns(db):
    """Upgrade every persisted Discord snowflake to PostgreSQL BIGINT.

    Existing text columns are validated before conversion so malformed legacy
    data aborts the migration rather than being silently coerced or lost.
    SQLite stores INTEGER values as signed 64-bit and does not need a type
    rewrite; the same schema remains compatible with local development.
    """
    if getattr(db, "backend", "sqlite") != "postgres":
        return

    columns = (
        ("users", "discord_id"),
        ("practice_games", "owner_discord_id"),
        ("matchmaking_queue", "discord_user_id"),
    )
    for table, column in columns:
        type_row = await (
            await db.execute(
                "SELECT data_type FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name=? AND column_name=?",
                (table, column),
            )
        ).fetchone()
        if not type_row or str(type_row["data_type"]).lower() == "bigint":
            continue

        # Text-backed legacy columns must contain numeric Discord snowflakes
        # before PostgreSQL can safely cast them to BIGINT.
        if str(type_row["data_type"]).lower() in {"text", "character varying", "varchar"}:
            invalid = await (
                await db.execute(
                    f"SELECT COUNT(*) AS count FROM {table} "
                    f"WHERE {column} IS NULL OR {column} !~ '^[0-9]+$'"
                )
            ).fetchone()
            if invalid and int(invalid["count"] or 0):
                raise RuntimeError(
                    f"Cannot migrate {table}.{column}: non-numeric Discord IDs present"
                )

        await db.execute(
            f"ALTER TABLE {table} ALTER COLUMN {column} TYPE BIGINT "
            f"USING {column}::BIGINT"
        )

    await record_version(db, DISCORD_ID_MIGRATION_VERSION)


async def ensure_competitive_profile(
    db,
    user_id,
    *,
    commit=True,
):
    await db.execute(
        """
        INSERT OR IGNORE INTO skill_ratings (
            user_id,
            pool,
            rating,
            peak_rating,
            rating_deviation,
            volatility,
            provisional,
            rated_games,
            model_version
        )
        VALUES (
            ?,
            ?,
            1500.0,
            1500.0,
            350.0,
            0.06,
            1,
            0,
            ?
        )
        """,
        (
            user_id,
            DEFAULT_RATING_POOL,
            CURRENT_RATING_MODEL,
        ),
    )

    await db.execute(
        """
        INSERT OR IGNORE INTO progression (
            user_id,
            sr,
            peak_sr,
            total_sr_earned,
            games_rewarded
        )
        VALUES (
            ?,
            2500,
            2500,
            0,
            0
        )
        """,
        (
            user_id,
        ),
    )

    if commit:
        await db.commit()


async def get_or_create_user(
    discord_id: int,
    username: str,
    display_name: str | None = None,
    avatar_url: str | None = None,
):
    db = await connect()

    try:
        await db.execute(
            """
            INSERT INTO users (
                discord_id,
                username,
                display_name,
                avatar_url
            )
            VALUES (?, ?, ?, ?)

            ON CONFLICT(discord_id)
            DO UPDATE SET
                username = excluded.username,
                display_name = excluded.display_name,
                avatar_url = excluded.avatar_url,
                updated_at = CURRENT_TIMESTAMP
            """,
            (
                discord_id,
                username,
                display_name,
                avatar_url,
            ),
        )

        await db.commit()

        cursor = await db.execute(
            """
            SELECT id
            FROM users
            WHERE discord_id = ?
            """,
            (
                discord_id,
            ),
        )

        row = await cursor.fetchone()

        if row is None:
            raise RuntimeError(
                "Failed to create or retrieve Bishoply user."
            )

        user_id = row["id"]

        await db.execute(
            """
            INSERT OR IGNORE INTO ratings (
                user_id
            )
            VALUES (?)
            """,
            (
                user_id,
            ),
        )

        await ensure_competitive_profile(
            db,
            user_id,
            commit=False,
        )

        await db.commit()

        return user_id

    finally:
        await db.close()
